// eslint-disable-next-line
export default {
    "nextjs": require("./images/1.webp"),
    "jeffdelaney": require("./images/6Avatar.webp"),
    "react":require("./images/7.png"),
    "nextj":require("./images/8.png"),
    "firebase": require("./images/9.png"),
    "klutch": require("./images/10.jpg"),
    "leeRobinson": require("./images/11.webp"),
    "johnGuest":require("./images/12.webp"),
    "books":require("./images/13.jpg"),
    "police":require("./images/14.png"),
    "fire":require("./images/15.png"),
    "atom":require("./images/16.png"),
    "joystick":require("./images/17.png"),
    "dna":require("./images/18.png"),
    "laptop":require("./images/19.png"),
    "monocole":require("./images/20.png"),
    "train":require("./images/21.png"),
    "counterclock":require("./images/22.png"),
    "chocolate":require("./images/23.png"),
    "butter":require("./images/24.png"),
    "holdinghand":require("./images/25.png"),
    "silhouette":require("./images/26.png"),
    "globe":require("./images/27.png"),
    "fishingpole":require("./images/28.png"),
    "magnifying":require("./images/29.png"),
    "floppydisk":require("./images/30.png"),
    "stop":require("./images/31.png"),
    "hearts":require("./images/32.png"),
    "lock": require("./images/33.png"),
    "logoWhiteArrow": require("./images/34.jfif"),
    "wordleWorkshop":require("./images/35.png"),
    "book":require("./images/36.png"),
    "clock": require("./images/37.png"),
    "jeffreyWay": require("./images/38.jpg"),
    "checkMark": require("./images/39.png"),
    "download": require("./images/40.png"),
    "fingerPrint":require("./images/41.png"),
    "dot": require("./images/42.png"),
    "menu":require("./images/43.png"),
    "frameworks": require("./images/44.png"),
    "signlock":require("./images/45.png"),
    "user":require("./images/46.png"),
    
}