import images from "../assests/images"
export const getTopicsData = () => {
    return [
    {
      id: 1,
      title: "AlpineJS",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 2,
      title: "Authentication",
      num_series: "3",
      num_videos: "30",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 3,
      title: "Billing",
      num_series: "1",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 4,
      title: "JavaScript",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 5,
      title: "Blade",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 6,
      title: "Clean Code",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 7,
      title: "CSS",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 8,
      title: "Cypress",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 9,
      title: "Deployment",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 10,
      title: "Docker",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 12,
      title: "EloquentS",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 13,
      title: "Envoyer",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 14,
      title: "Git",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 15,
      title: "GraphQL",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 16,
      title: "Inertia",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 17,
      title: "Laravel",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 18,
      title: "Laravel Cashier",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 19,
      title: "Laravel Forge",
      num_series: "7",
      num_videos: "86",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 20,
      title: "Laravel Livewire",
      num_series: "3",
      num_videos: "30",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 21,
      title: "Laravel Mix",
      num_series: "3",
      num_videos: "30",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 21,
      title: "Laravel Packages",
      num_series: "3",
      num_videos: "30",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 22,
      title: "MySQL",
      num_series: "3",
      num_videos: "30",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 23,
      title: "Nova",
      num_series: "3",
      num_videos: "30",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 24,
      title: "Nuxt",
      num_series: "3",
      num_videos: "30",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 25,
      title: "OOP",
      num_series: "3",
      num_videos: "30",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
    {
      id: 26,
      title: "Pest",
      num_series: "3",
      num_videos: "30",
      topic_image: images.fingerPrint,
      dot_image: images.dot,
    },
  ];
    
};